import Foundation
import WebKit

enum BrowserUserAgent {
    static var applicationName: String {
        "Version/\(installedSafariVersion) Safari/605.1.15"
    }

    private static var installedSafariVersion: String {
        let version = Bundle(path: "/Applications/Safari.app")?
            .object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String

        if let version, let normalized = normalize(version) {
            return normalized
        }

        let macOSMajor = ProcessInfo.processInfo.operatingSystemVersion.majorVersion
        let safariMajor = macOSMajor >= 26 ? macOSMajor : macOSMajor + 3
        return "\(safariMajor).0"
    }

    private static func normalize(_ version: String) -> String? {
        let components = version
            .split(separator: ".")
            .prefix(3)
            .compactMap { Int($0) }
        guard !components.isEmpty else { return nil }
        return components.map(String.init).joined(separator: ".")
    }
}

@MainActor
struct WebViewFactory {
    private let configuration: BrowserConfiguration

    init(configuration: BrowserConfiguration) {
        self.configuration = configuration
    }

    func makeWebView() -> WKWebView {
        makeWebView(configuration: configuration.makeWebViewConfiguration())
    }

    func makePrivateWebView() -> WKWebView {
        let privateConfiguration = configuration.makeWebViewConfiguration()
        privateConfiguration.websiteDataStore = .nonPersistent()
        return makeWebView(configuration: privateConfiguration)
    }

    func makeWebView(configuration: WKWebViewConfiguration) -> WKWebView {
        if configuration.applicationNameForUserAgent?.isEmpty != false {
            // The stock macOS WKWebView user agent has no Version/Safari
            // product token. Google consequently serves its legacy fallback
            // UI even though the underlying WebKit engine is current.
            configuration.applicationNameForUserAgent = BrowserUserAgent.applicationName
        }
        let webView = WKWebView(frame: .zero, configuration: configuration)
        webView.allowsBackForwardNavigationGestures = true
        webView.allowsMagnification = true
        // Keep the engine and OS portion generated by WebKit. The configuration
        // above only adds the product token websites expect from Safari.
        webView.customUserAgent = nil
        return webView
    }
}
